# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dms.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('cityname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sort', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=45)),
                ('img', models.ImageField(storage=dms.storage.ImageStorage(), upload_to='./commodityimg/')),
            ],
        ),
        migrations.CreateModel(
            name='delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='delegation_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TimeField()),
                ('remask', models.CharField(max_length=45)),
                ('delegation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.delegation')),
            ],
        ),
        migrations.CreateModel(
            name='indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TimeField()),
                ('remask', models.CharField(max_length=45)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=20)),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.city')),
            ],
        ),
        migrations.CreateModel(
            name='security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('age', models.IntegerField()),
                ('introduce', models.CharField(blank=True, max_length=45)),
                ('unique', models.CharField(max_length=45)),
                ('portrait', models.CharField(blank=True, max_length=45)),
                ('addressid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressid', to='dms.location')),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.campus')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationid', to='dms.location')),
                ('security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.security')),
            ],
        ),
        migrations.AddField(
            model_name='indent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.location'),
        ),
        migrations.AddField(
            model_name='indent',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.user'),
        ),
        migrations.AddField(
            model_name='delegation_order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.user'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.user'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.location'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.user'),
        ),
        migrations.AddField(
            model_name='collection',
            name='commodity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.commodity'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.user'),
        ),
    ]
